// Package swagger provides HTTP handlers for API documentation.
// This includes Swagger JSON and API information endpoints.
package swagger

import (
	"github.com/logistics-id/engine/transport/rest"
	_ "github.com/logistics-id/onward-tms/docs" // Swagger docs (generated)
)

type handler struct{}

// GetSwaggerJSON serves swagger.json documentation
// @Summary Get API documentation (Swagger JSON)
// @Description Get Swagger API documentation in JSON format
// @Tags docs
// @Produce json
// @Router /docs/swagger.json [get]
func (h *handler) GetSwaggerJSON(ctx *rest.Context) error {
	// The swagger.json is generated by swag CLI and located at docs/swagger/swagger.json
	// This endpoint indicates where to find the documentation
	return ctx.Respond(rest.NewResponseBody(map[string]string{
		"message": "API documentation available",
		"swagger": "/docs/swagger.json",
		"yaml":    "/docs/swagger.yaml",
		"info":    "Run 'swag init' to regenerate docs after adding annotations",
	}), nil)
}

// GetInfo serves API information
// @Summary Get API Information
// @Description Get basic information about the TMS Onward API
// @Tags docs
// @Produce json
// @Router /docs/info [get]
func (h *handler) GetInfo(ctx *rest.Context) error {
	return ctx.Respond(rest.NewResponseBody(map[string]interface{}{
		"title":       "TMS Onward API",
		"description": "Transportation Management System API for logistics companies",
		"version":     "1.0",
		"endpoints": map[string]string{
			"swagger_json": "/docs/swagger.json",
			"swagger_yaml": "/docs/swagger.yaml",
		},
		"documentation": "Swagger/OpenAPI 2.0 specification",
	}), nil)
}

// RegisterHandler registers the swagger documentation routes
func RegisterHandler(s *rest.RestServer) {
	h := &handler{}

	// Register swagger endpoints - public routes (no authentication required)
	s.GET("/docs/swagger.json", h.GetSwaggerJSON, nil)
	s.GET("/docs/info", h.GetInfo, nil)
}
