// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: tms.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignupRequest - Request for user registration
type SignupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Company data
	CompanyName string `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// User data
	Username        string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Email           string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password        string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string `protobuf:"bytes,7,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Phone           string `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_tms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *SignupRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *SignupRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// SignupResponse - Response after successful signup
type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_tms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{1}
}

func (x *SignupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FindCompanyByNameRequest - Request to find company by name
type FindCompanyByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCompanyByNameRequest) Reset() {
	*x = FindCompanyByNameRequest{}
	mi := &file_tms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCompanyByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCompanyByNameRequest) ProtoMessage() {}

func (x *FindCompanyByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCompanyByNameRequest.ProtoReflect.Descriptor instead.
func (*FindCompanyByNameRequest) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{2}
}

func (x *FindCompanyByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// FindCompanyByNameResponse - Response with company exists status
type FindCompanyByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCompanyByNameResponse) Reset() {
	*x = FindCompanyByNameResponse{}
	mi := &file_tms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCompanyByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCompanyByNameResponse) ProtoMessage() {}

func (x *FindCompanyByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCompanyByNameResponse.ProtoReflect.Descriptor instead.
func (*FindCompanyByNameResponse) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{3}
}

func (x *FindCompanyByNameResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// FindUserByEmailRequest - Request to find user by email
type FindUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserByEmailRequest) Reset() {
	*x = FindUserByEmailRequest{}
	mi := &file_tms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByEmailRequest) ProtoMessage() {}

func (x *FindUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*FindUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{4}
}

func (x *FindUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// FindUserByEmailResponse - Response with user exists status
type FindUserByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserByEmailResponse) Reset() {
	*x = FindUserByEmailResponse{}
	mi := &file_tms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByEmailResponse) ProtoMessage() {}

func (x *FindUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*FindUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{5}
}

func (x *FindUserByEmailResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// FindUserByUsernameRequest - Request to find user by email
type FindUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserByUsernameRequest) Reset() {
	*x = FindUserByUsernameRequest{}
	mi := &file_tms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByUsernameRequest) ProtoMessage() {}

func (x *FindUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*FindUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{6}
}

func (x *FindUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// FindUserByUsernameResponse - Response with user exists status
type FindUserByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserByUsernameResponse) Reset() {
	*x = FindUserByUsernameResponse{}
	mi := &file_tms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByUsernameResponse) ProtoMessage() {}

func (x *FindUserByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByUsernameResponse.ProtoReflect.Descriptor instead.
func (*FindUserByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{7}
}

func (x *FindUserByUsernameResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// DashboardSummary - Summary statistics for superadmin
type DashboardSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalTenants   int64                  `protobuf:"varint,1,opt,name=total_tenants,json=totalTenants,proto3" json:"total_tenants,omitempty"`
	TotalShipments int64                  `protobuf:"varint,2,opt,name=total_shipments,json=totalShipments,proto3" json:"total_shipments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardSummary) Reset() {
	*x = DashboardSummary{}
	mi := &file_tms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummary) ProtoMessage() {}

func (x *DashboardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummary.ProtoReflect.Descriptor instead.
func (*DashboardSummary) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{8}
}

func (x *DashboardSummary) GetTotalTenants() int64 {
	if x != nil {
		return x.TotalTenants
	}
	return 0
}

func (x *DashboardSummary) GetTotalShipments() int64 {
	if x != nil {
		return x.TotalShipments
	}
	return 0
}

// CompanyData - Company shipment data
type CompanyData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompanyName    string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	TotalShipments int64                  `protobuf:"varint,2,opt,name=total_shipments,json=totalShipments,proto3" json:"total_shipments,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompanyData) Reset() {
	*x = CompanyData{}
	mi := &file_tms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyData) ProtoMessage() {}

func (x *CompanyData) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyData.ProtoReflect.Descriptor instead.
func (*CompanyData) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{9}
}

func (x *CompanyData) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CompanyData) GetTotalShipments() int64 {
	if x != nil {
		return x.TotalShipments
	}
	return 0
}

func (x *CompanyData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// DashboardRequest - Request with optional month filter
type DashboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional month filter in format "YYYY-MM" (e.g., "2025-03")
	// If empty, returns all-time statistics
	Monthly       string `protobuf:"bytes,1,opt,name=monthly,proto3" json:"monthly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRequest) Reset() {
	*x = DashboardRequest{}
	mi := &file_tms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRequest) ProtoMessage() {}

func (x *DashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRequest.ProtoReflect.Descriptor instead.
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{10}
}

func (x *DashboardRequest) GetMonthly() string {
	if x != nil {
		return x.Monthly
	}
	return ""
}

// DashboardResponse - Response with summary data
type DashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *DashboardSummary      `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Companies     []*CompanyData         `protobuf:"bytes,2,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_tms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{11}
}

func (x *DashboardResponse) GetSummary() *DashboardSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *DashboardResponse) GetCompanies() []*CompanyData {
	if x != nil {
		return x.Companies
	}
	return nil
}

var File_tms_proto protoreflect.FileDescriptor

const file_tms_proto_rawDesc = "" +
	"\n" +
	"\ttms.proto\x12\x03tms\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\rSignupRequest\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\a \x01(\tR\x0fconfirmPassword\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\"*\n" +
	"\x0eSignupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x18FindCompanyByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x19FindCompanyByNameResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\".\n" +
	"\x16FindUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"1\n" +
	"\x17FindUserByEmailResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"7\n" +
	"\x19FindUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"4\n" +
	"\x1aFindUserByUsernameResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"`\n" +
	"\x10DashboardSummary\x12#\n" +
	"\rtotal_tenants\x18\x01 \x01(\x03R\ftotalTenants\x12'\n" +
	"\x0ftotal_shipments\x18\x02 \x01(\x03R\x0etotalShipments\"\x94\x01\n" +
	"\vCompanyData\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12'\n" +
	"\x0ftotal_shipments\x18\x02 \x01(\x03R\x0etotalShipments\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x10DashboardRequest\x12\x18\n" +
	"\amonthly\x18\x01 \x01(\tR\amonthly\"t\n" +
	"\x11DashboardResponse\x12/\n" +
	"\asummary\x18\x01 \x01(\v2\x15.tms.DashboardSummaryR\asummary\x12.\n" +
	"\tcompanies\x18\x02 \x03(\v2\x10.tms.CompanyDataR\tcompanies2\xf7\x02\n" +
	"\n" +
	"TMSService\x121\n" +
	"\x06Signup\x12\x12.tms.SignupRequest\x1a\x13.tms.SignupResponse\x12R\n" +
	"\x11FindCompanyByName\x12\x1d.tms.FindCompanyByNameRequest\x1a\x1e.tms.FindCompanyByNameResponse\x12L\n" +
	"\x0fFindUserByEmail\x12\x1b.tms.FindUserByEmailRequest\x1a\x1c.tms.FindUserByEmailResponse\x12U\n" +
	"\x12FindUserByUsername\x12\x1e.tms.FindUserByUsernameRequest\x1a\x1f.tms.FindUserByUsernameResponse\x12=\n" +
	"\fGetDashboard\x12\x15.tms.DashboardRequest\x1a\x16.tms.DashboardResponseB0Z.github.com/logistics-id/onward-tms/proto;protob\x06proto3"

var (
	file_tms_proto_rawDescOnce sync.Once
	file_tms_proto_rawDescData []byte
)

func file_tms_proto_rawDescGZIP() []byte {
	file_tms_proto_rawDescOnce.Do(func() {
		file_tms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tms_proto_rawDesc), len(file_tms_proto_rawDesc)))
	})
	return file_tms_proto_rawDescData
}

var file_tms_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tms_proto_goTypes = []any{
	(*SignupRequest)(nil),              // 0: tms.SignupRequest
	(*SignupResponse)(nil),             // 1: tms.SignupResponse
	(*FindCompanyByNameRequest)(nil),   // 2: tms.FindCompanyByNameRequest
	(*FindCompanyByNameResponse)(nil),  // 3: tms.FindCompanyByNameResponse
	(*FindUserByEmailRequest)(nil),     // 4: tms.FindUserByEmailRequest
	(*FindUserByEmailResponse)(nil),    // 5: tms.FindUserByEmailResponse
	(*FindUserByUsernameRequest)(nil),  // 6: tms.FindUserByUsernameRequest
	(*FindUserByUsernameResponse)(nil), // 7: tms.FindUserByUsernameResponse
	(*DashboardSummary)(nil),           // 8: tms.DashboardSummary
	(*CompanyData)(nil),                // 9: tms.CompanyData
	(*DashboardRequest)(nil),           // 10: tms.DashboardRequest
	(*DashboardResponse)(nil),          // 11: tms.DashboardResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_tms_proto_depIdxs = []int32{
	12, // 0: tms.CompanyData.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: tms.DashboardResponse.summary:type_name -> tms.DashboardSummary
	9,  // 2: tms.DashboardResponse.companies:type_name -> tms.CompanyData
	0,  // 3: tms.TMSService.Signup:input_type -> tms.SignupRequest
	2,  // 4: tms.TMSService.FindCompanyByName:input_type -> tms.FindCompanyByNameRequest
	4,  // 5: tms.TMSService.FindUserByEmail:input_type -> tms.FindUserByEmailRequest
	6,  // 6: tms.TMSService.FindUserByUsername:input_type -> tms.FindUserByUsernameRequest
	10, // 7: tms.TMSService.GetDashboard:input_type -> tms.DashboardRequest
	1,  // 8: tms.TMSService.Signup:output_type -> tms.SignupResponse
	3,  // 9: tms.TMSService.FindCompanyByName:output_type -> tms.FindCompanyByNameResponse
	5,  // 10: tms.TMSService.FindUserByEmail:output_type -> tms.FindUserByEmailResponse
	7,  // 11: tms.TMSService.FindUserByUsername:output_type -> tms.FindUserByUsernameResponse
	11, // 12: tms.TMSService.GetDashboard:output_type -> tms.DashboardResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tms_proto_init() }
func file_tms_proto_init() {
	if File_tms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tms_proto_rawDesc), len(file_tms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tms_proto_goTypes,
		DependencyIndexes: file_tms_proto_depIdxs,
		MessageInfos:      file_tms_proto_msgTypes,
	}.Build()
	File_tms_proto = out.File
	file_tms_proto_goTypes = nil
	file_tms_proto_depIdxs = nil
}
