// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: tms.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DashboardSummary - Summary statistics for superadmin
type DashboardSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalTenants   int64                  `protobuf:"varint,1,opt,name=total_tenants,json=totalTenants,proto3" json:"total_tenants,omitempty"`
	TotalShipments int64                  `protobuf:"varint,2,opt,name=total_shipments,json=totalShipments,proto3" json:"total_shipments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardSummary) Reset() {
	*x = DashboardSummary{}
	mi := &file_tms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummary) ProtoMessage() {}

func (x *DashboardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummary.ProtoReflect.Descriptor instead.
func (*DashboardSummary) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardSummary) GetTotalTenants() int64 {
	if x != nil {
		return x.TotalTenants
	}
	return 0
}

func (x *DashboardSummary) GetTotalShipments() int64 {
	if x != nil {
		return x.TotalShipments
	}
	return 0
}

// GetSummaryRequest - Request with optional month filter
type GetSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional month filter in format "YYYY-MM" (e.g., "2025-03")
	// If empty, returns all-time statistics
	Month         string `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_tms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{1}
}

func (x *GetSummaryRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

// GetSummaryResponse - Response with summary data
type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *DashboardSummary      `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_tms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_tms_proto_rawDescGZIP(), []int{2}
}

func (x *GetSummaryResponse) GetSummary() *DashboardSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

var File_tms_proto protoreflect.FileDescriptor

const file_tms_proto_rawDesc = "" +
	"\n" +
	"\ttms.proto\x12\x03tms\"`\n" +
	"\x10DashboardSummary\x12#\n" +
	"\rtotal_tenants\x18\x01 \x01(\x03R\ftotalTenants\x12'\n" +
	"\x0ftotal_shipments\x18\x02 \x01(\x03R\x0etotalShipments\")\n" +
	"\x11GetSummaryRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\"E\n" +
	"\x12GetSummaryResponse\x12/\n" +
	"\asummary\x18\x01 \x01(\v2\x15.tms.DashboardSummaryR\asummary2K\n" +
	"\n" +
	"TMSService\x12=\n" +
	"\n" +
	"GetSummary\x12\x16.tms.GetSummaryRequest\x1a\x17.tms.GetSummaryResponseB0Z.github.com/logistics-id/onward-tms/proto;protob\x06proto3"

var (
	file_tms_proto_rawDescOnce sync.Once
	file_tms_proto_rawDescData []byte
)

func file_tms_proto_rawDescGZIP() []byte {
	file_tms_proto_rawDescOnce.Do(func() {
		file_tms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tms_proto_rawDesc), len(file_tms_proto_rawDesc)))
	})
	return file_tms_proto_rawDescData
}

var file_tms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tms_proto_goTypes = []any{
	(*DashboardSummary)(nil),   // 0: tms.DashboardSummary
	(*GetSummaryRequest)(nil),  // 1: tms.GetSummaryRequest
	(*GetSummaryResponse)(nil), // 2: tms.GetSummaryResponse
}
var file_tms_proto_depIdxs = []int32{
	0, // 0: tms.GetSummaryResponse.summary:type_name -> tms.DashboardSummary
	1, // 1: tms.TMSService.GetSummary:input_type -> tms.GetSummaryRequest
	2, // 2: tms.TMSService.GetSummary:output_type -> tms.GetSummaryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tms_proto_init() }
func file_tms_proto_init() {
	if File_tms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tms_proto_rawDesc), len(file_tms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tms_proto_goTypes,
		DependencyIndexes: file_tms_proto_depIdxs,
		MessageInfos:      file_tms_proto_msgTypes,
	}.Build()
	File_tms_proto = out.File
	file_tms_proto_goTypes = nil
	file_tms_proto_depIdxs = nil
}
