// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: tms.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TMSService_GetSummary_FullMethodName = "/tms.TMSService/GetSummary"
)

// TMSServiceClient is the client API for TMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TMSServiceClient interface {
	// Dashboard operations
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error)
}

type tMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTMSServiceClient(cc grpc.ClientConnInterface) TMSServiceClient {
	return &tMSServiceClient{cc}
}

func (c *tMSServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryResponse)
	err := c.cc.Invoke(ctx, TMSService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TMSServiceServer is the server API for TMSService service.
// All implementations must embed UnimplementedTMSServiceServer
// for forward compatibility.
type TMSServiceServer interface {
	// Dashboard operations
	GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error)
	mustEmbedUnimplementedTMSServiceServer()
}

// UnimplementedTMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTMSServiceServer struct{}

func (UnimplementedTMSServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedTMSServiceServer) mustEmbedUnimplementedTMSServiceServer() {}
func (UnimplementedTMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TMSServiceServer will
// result in compilation errors.
type UnsafeTMSServiceServer interface {
	mustEmbedUnimplementedTMSServiceServer()
}

func RegisterTMSServiceServer(s grpc.ServiceRegistrar, srv TMSServiceServer) {
	// If the following call pancis, it indicates UnimplementedTMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TMSService_ServiceDesc, srv)
}

func _TMSService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TMSService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TMSService_ServiceDesc is the grpc.ServiceDesc for TMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tms.TMSService",
	HandlerType: (*TMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummary",
			Handler:    _TMSService_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tms.proto",
}
