// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: tms.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TMSService_Signup_FullMethodName             = "/tms.TMSService/Signup"
	TMSService_FindCompanyByName_FullMethodName  = "/tms.TMSService/FindCompanyByName"
	TMSService_FindUserByEmail_FullMethodName    = "/tms.TMSService/FindUserByEmail"
	TMSService_FindUserByUsername_FullMethodName = "/tms.TMSService/FindUserByUsername"
	TMSService_GetDashboard_FullMethodName       = "/tms.TMSService/GetDashboard"
)

// TMSServiceClient is the client API for TMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TMSServiceClient interface {
	// Auth operations
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	FindCompanyByName(ctx context.Context, in *FindCompanyByNameRequest, opts ...grpc.CallOption) (*FindCompanyByNameResponse, error)
	FindUserByEmail(ctx context.Context, in *FindUserByEmailRequest, opts ...grpc.CallOption) (*FindUserByEmailResponse, error)
	FindUserByUsername(ctx context.Context, in *FindUserByUsernameRequest, opts ...grpc.CallOption) (*FindUserByUsernameResponse, error)
	// Dashboard operations
	GetDashboard(ctx context.Context, in *DashboardRequest, opts ...grpc.CallOption) (*DashboardResponse, error)
}

type tMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTMSServiceClient(cc grpc.ClientConnInterface) TMSServiceClient {
	return &tMSServiceClient{cc}
}

func (c *tMSServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, TMSService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSServiceClient) FindCompanyByName(ctx context.Context, in *FindCompanyByNameRequest, opts ...grpc.CallOption) (*FindCompanyByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCompanyByNameResponse)
	err := c.cc.Invoke(ctx, TMSService_FindCompanyByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSServiceClient) FindUserByEmail(ctx context.Context, in *FindUserByEmailRequest, opts ...grpc.CallOption) (*FindUserByEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindUserByEmailResponse)
	err := c.cc.Invoke(ctx, TMSService_FindUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSServiceClient) FindUserByUsername(ctx context.Context, in *FindUserByUsernameRequest, opts ...grpc.CallOption) (*FindUserByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindUserByUsernameResponse)
	err := c.cc.Invoke(ctx, TMSService_FindUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSServiceClient) GetDashboard(ctx context.Context, in *DashboardRequest, opts ...grpc.CallOption) (*DashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardResponse)
	err := c.cc.Invoke(ctx, TMSService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TMSServiceServer is the server API for TMSService service.
// All implementations must embed UnimplementedTMSServiceServer
// for forward compatibility.
type TMSServiceServer interface {
	// Auth operations
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	FindCompanyByName(context.Context, *FindCompanyByNameRequest) (*FindCompanyByNameResponse, error)
	FindUserByEmail(context.Context, *FindUserByEmailRequest) (*FindUserByEmailResponse, error)
	FindUserByUsername(context.Context, *FindUserByUsernameRequest) (*FindUserByUsernameResponse, error)
	// Dashboard operations
	GetDashboard(context.Context, *DashboardRequest) (*DashboardResponse, error)
	mustEmbedUnimplementedTMSServiceServer()
}

// UnimplementedTMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTMSServiceServer struct{}

func (UnimplementedTMSServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedTMSServiceServer) FindCompanyByName(context.Context, *FindCompanyByNameRequest) (*FindCompanyByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCompanyByName not implemented")
}
func (UnimplementedTMSServiceServer) FindUserByEmail(context.Context, *FindUserByEmailRequest) (*FindUserByEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserByEmail not implemented")
}
func (UnimplementedTMSServiceServer) FindUserByUsername(context.Context, *FindUserByUsernameRequest) (*FindUserByUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserByUsername not implemented")
}
func (UnimplementedTMSServiceServer) GetDashboard(context.Context, *DashboardRequest) (*DashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedTMSServiceServer) mustEmbedUnimplementedTMSServiceServer() {}
func (UnimplementedTMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TMSServiceServer will
// result in compilation errors.
type UnsafeTMSServiceServer interface {
	mustEmbedUnimplementedTMSServiceServer()
}

func RegisterTMSServiceServer(s grpc.ServiceRegistrar, srv TMSServiceServer) {
	// If the following call panics, it indicates UnimplementedTMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TMSService_ServiceDesc, srv)
}

func _TMSService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TMSService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSService_FindCompanyByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCompanyByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSServiceServer).FindCompanyByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TMSService_FindCompanyByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSServiceServer).FindCompanyByName(ctx, req.(*FindCompanyByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSService_FindUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSServiceServer).FindUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TMSService_FindUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSServiceServer).FindUserByEmail(ctx, req.(*FindUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSService_FindUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSServiceServer).FindUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TMSService_FindUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSServiceServer).FindUserByUsername(ctx, req.(*FindUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TMSService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSServiceServer).GetDashboard(ctx, req.(*DashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TMSService_ServiceDesc is the grpc.ServiceDesc for TMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tms.TMSService",
	HandlerType: (*TMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _TMSService_Signup_Handler,
		},
		{
			MethodName: "FindCompanyByName",
			Handler:    _TMSService_FindCompanyByName_Handler,
		},
		{
			MethodName: "FindUserByEmail",
			Handler:    _TMSService_FindUserByEmail_Handler,
		},
		{
			MethodName: "FindUserByUsername",
			Handler:    _TMSService_FindUserByUsername_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _TMSService_GetDashboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tms.proto",
}
