replicaCount: 1

image:
  repository: enivent/svc-tms
  tag: latest

service:
  type: ClusterIP
  restPort: 80
  grpcPort: 40

containerPort: 80
containerGRPCPort: 40

global:
  domain: ""
  tlsSecret: ""

env:
  - name: DEBUG_MODE
    value: "true"
  - name: PLATFORM
    value: "logistics-id"
  - name: POSTGRES_DATABASE
    value: "onward_tms"
  - name: MONGODB_DATABASE
    value: "onward_tms"
  - name: S3_BUCKET_NAME
    value: "onward.prod"
  - name: AWS_REGION
    value: "ap-southeast-3"
  - name: AWS_ACCESS_KEY_ID
    value: "AKIAW7FYE2IYJKXITVAN"
  - name: AWS_SECRET_ACCESS_KEY
    value: "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"
