apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc-tms
  labels:
    app: svc-tms
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: "https"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - {{ required "global.domain is required" .Values.global.domain }}
      secretName:
        {{ required "global.tlsSecret is required" .Values.global.tlsSecret }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /tms
            pathType: Prefix
            backend:
              service:
                name: svc-tms
                port:
                  number: 80
