apiVersion: v1
kind: Service
metadata:
  name: svc-tms
  labels:
    app: svc-tms
spec:
  type: {{ .Values.service.type }}
  selector:
    app: svc-tms
  ports:
    - name: http
      port: {{ .Values.service.restPort }}
      targetPort: {{ .Values.containerPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.containerGRPCPort }}
