apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dev-warehouse/ds-rabbitmq
  hostPath:
    path: /data/dev-warehouse/rabbitmq
