apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-rabbitmq
  namespace: dev-warehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
